# backend — use glx for best compatibility
backend = "glx";

# disable all animations
no-fading-openclose = true;
no-fading-destroyed-argb = true;
fading = false;

# disable shadows
shadow = false;

# disable blur
blur-method = "none";

# vsync to prevent screen tearing
vsync = true;

# needed for rounded corners in dunst/notifications
# round notification and window corners
corner-radius = 10;

# exclude bars from rounding
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'i3bar'",
  "class_g = 'kitty'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
# transparency — disable
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
