wallpaper {
    monitor =  eDP-1
    path = /home/eddie/opt/WALLPAPER_FS01/ENDEAVOUR_OS/eos_wallpapers_classic/atlantis-neo-livewall.png
}

wallpaper {
    monitor =  HDMI-A-2
    path = /home/eddie/opt/WALLPAPER_FS01/ARCH-LINUX/4537026.png
}
