wallpaper {
    monitor =  eDP-1
    path = /home/eddie/opt/WALLPAPER_FS01/HYPRLAND/shaded_landscape.png
}

wallpaper {
    monitor =  HDMI-A-2
    path = /home/eddie/opt/WALLPAPER_FS01/HYPRLAND/car-with-full-moon-background.jpg
}
