;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; gruvbox dark color scheme

;; main colors
background     = #282828
foreground     = #ebdbb2
foreground-alt = #a89984
module-fg      = #282828

;; accent colors
primary        = #d79921
secondary      = #cc241d
alternate      = #98971a

;; full gruvbox palette (for use in modules)
gb-red         = #cc241d
gb-green       = #98971a
gb-yellow      = #d79921
gb-blue        = #458588
gb-purple      = #b16286
gb-aqua        = #689d6a
gb-orange      = #d65d0e
gb-gray        = #928374

gb-red-bright     = #fb4934
gb-green-bright   = #b8bb26
gb-yellow-bright  = #fabd2f
gb-blue-bright    = #83a598
gb-purple-bright  = #d3869b
gb-aqua-bright    = #8ec07c
gb-orange-bright  = #fe8019

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
