# INPUTS
input "5215:621:SINOWEALTH_GXT_144_Gaming_Mouse" {
    # accel_profile flat
    pointer_accel -0.5
}

input type:touchpad {
    tap enabled
    tap_button_map lrm
    natural_scroll disabled
    scroll_method two_finger
    dwt enabled
}

input type:keyboard {
    xkb_layout us
    xkb_model pc105
    xkb_variant altgr-intl
    repeat_delay 250
    repeat_rate 40
    xkb_numlock enabled
}
