###################################################
# INPUTS

###################################################
# defaults
input type:touchpad {
    tap enabled
    tap_button_map lrm
    natural_scroll disabled
    scroll_method two_finger
    dwt enabled
    pointer_accel -0.2
    scroll_factor 0.2
    accel_profile adaptive
}

input type:keyboard {
    xkb_layout de
    xkb_variant us
    xkb_model pc105
    repeat_delay 250
    repeat_rate 40
    xkb_numlock enabled
}

###################################################
# customs
input "5215:621:SINOWEALTH_GXT_144_Gaming_Mouse" {
    accel_profile flat
    pointer_accel -0.5
}

input "9610:10:SINO_WEALTH_PERIPAD-506_Touchpad" {
    pointer_accel -0.5
    scroll_factor 0.2
}

input "9610:10:SINO_WEALTH_PERIPAD-506_Mouse" {
    pointer_accel -0.5
    scroll_factor 0.2
    accel_profile adaptive
}

seat * xcursor_theme "Breeze_Light" 26
